title: Henrique's blog
email: henr.asilva@gmail.com
domain: henrique-silva.github.io
url: https://henrique-silva.github.io
github_username:  henrique-silva

remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jemoji